### ISSUE TITLE
Link user login process to coorporate LDAP instance

### ISSUE THREAD

**Issue by jens-markussen** [HewlettPackard/yoda-demo2#4]
> partof #8 [T2 - Story]  *test issue*

> partof HewlettPackard/yoda-demo#155 *Linking to org issues - testing*

> partof #6 [S1 - Urgent, T5 - Bug]  *Graph feature does not work on Mondays.*

> contains (total estimate: 0, total remaining: 0, # open issues: 1, # closed issues: 0)
- #6 [S1 - Urgent, T5 - Bug] 
  
> estimate 10
> remaining 2018-02-09 7

Yoda must be able configure user accesss to take place by cooperated LDAP instance at http://acme.mee.too/someorg/ldap. This has also been requested by senior management, Mr. R Runner.

This requires the following tasks:
- [x] Discuss LDAP set-up with cooperate IT.
- [ ] Implement LDAP plug-in module #5 
- [ ] Test LDAP plug-in module.
